version: 2.1

orbs:
  queue: eddiewebb/queue@1.6.4
  slack: circleci/slack@4.8.3

defaults: &defaults
  docker:
    - image: ruby:3.1.1

slack_context: &slack_context
  context:
    - slack

only_main: &only_main
  filters:
    branches:
      only:
        - main

only_dependabot: &only_dependabot
  filters:
    branches:
      only:
        - /^dependabot.*/

only_main_and_dependabot: &only_main_and_dependabot
  filters:
    branches:
      only:
        - main
        - /^dependabot.*/

commands:
  notify:
    steps:
      - slack/notify:
          event: fail
          channel: dev
          template: SLACK_FAILURE_NOTIFICATION
      - slack/notify:
          event: pass
          channel: builds
          template: SLACK_SUCCESS_NOTIFICATION
  configure_tools:
    steps:
      - run: ./scripts/ci/common/install-git-crypt.sh
      - run: ./scripts/ci/common/install-gpg-key.sh
      - run: ./scripts/ci/common/install-orb-deps.sh
      - run: ./scripts/ci/common/configure-git.sh

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - configure_tools
      - queue/until_front_of_line:
          consider-branch: false
      - run: ./scripts/ci/steps/test.sh
      - notify

  prerelease:
    <<: *defaults
    steps:
      - checkout
      - configure_tools
      - run: ./scripts/ci/steps/prerelease.sh
      - notify

  release:
    <<: *defaults
    steps:
      - checkout
      - configure_tools
      - run: ./scripts/ci/steps/release.sh
      - notify

  merge_pull_request:
    <<: *defaults
    steps:
      - checkout
      - configure_tools
      - run: ./scripts/ci/steps/merge-pull-request.sh
      - notify

workflows:
  version: 2
  pipeline:
    jobs:
      - test:
          <<: *slack_context
          <<: *only_main_and_dependabot
      - merge_pull_request:
          <<: *slack_context
          <<: *only_dependabot
          requires:
            - test
      - prerelease:
          <<: *slack_context
          <<: *only_main
          requires:
            - test
      - hold:
          <<: *only_main
          type: approval
          requires:
            - prerelease
      - release:
          <<: *slack_context
          <<: *only_main
          requires:
            - hold
