---
configuration_directory: "%{cwd}/spec/unit/infra/prerequisites"
state_file: "%{cwd}/state/prerequisites.tfstate"
vars:
  region: "%{hiera('region')}"

  vpc_cidr: "%{hiera('vpc_cidr')}"
  availability_zones: "%{hiera('availability_zones')}"

  component: "%{hiera('component')}"
  deployment_identifier: "%{hiera('deployment_identifier')}"

  private_zone_vpc_id: "%{hiera('private_zone_vpc_id')}"
